### ISSUE TITLE
Could this be usable with TypeScript?

### ISSUE THREAD

**Issue by claremacrae** [eliasm307/mustache-validator#1]
Hi, thanks for writing this. It looks very exciting.

I tried using it in a TypeScript project and WebStorm told me to run:

```bash
 yarn add @types/mustache-validator --dev
```

This gives me:

```test
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fmustache-validator: Not found".
info If you think this is a bug, please open a bug report with the information provided in ".../yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I've no idea if you're still maintaining this - and I don't know enough about TypeScript to know how to fix this - but on the off-chance that you are, I thought I would ask...

**Comment by eliasm307** [comment]
Hey, I've fixed the types for the published package as part of this commit https://github.com/eliasm307/mustache-validator/commit/e266e7fe606482a7cc87e21b194ddb6bf00dd269

Try using v0.2

**Comment by claremacrae** [comment]
Brilliant - very many thanks indeed!

**Comment by claremacrae** [comment]
It works great. Thank you very much again! ❤️
